### ISSUE TITLE
`status_store` config seems unused

### ISSUE THREAD

**Issue by Dantemss** [lml/lev#31]
Instead, the code serializes the routine status as part of the job arguments.

**Comment by jpslav** [comment]
`status_store` is supposed to be set to redis when used in an app like tutor

**Comment by Dantemss** [comment]
Yeah but the code never uses it...

**Comment by jpslav** [comment]
should be used, otherwise status will no worky I believe (moral is don't take it out of here since it is supposed to be used by apps that use lev)

**Comment by Dantemss** [comment]
Don't see it: https://github.com/lml/lev/search?q=status_store&type=Code

**Comment by Dantemss** [comment]
Nvm I see it now...
